repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
    -   id: isort
        types: [python]
        args: [
        "--settings-path", "setup.cfg"
    ]

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.6

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [
            flake8-bandit,
            flake8-bugbear
        ]
        language: python
        types: [python]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude_types: [json]
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: python-check-mock-methods
    -   id: python-use-type-annotations
    -   id: python-no-eval

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
        args: ["--config-file", "setup.cfg"]
